### PR TITLE
fix+refact(system-cleanup)

### LINKED ISSUE #855: Full System Cleanup doesn't clean Trash if it errors out on cleaning cache
## Describe the bug
Full System Cleanup doesn't perform all tasks because one of these independent tasks has failed. When cleaning the cache can't run (in this case because .cache doesn't exist), the script ends and doesn't run Trash cleanup

## To Reproduce
1. Disable/Stop any processes that write to .cache (including Starship)
2. Remove `~/.cache`
3. Run System Disk Cleanup from Linutil
4. Select y to clean up Cache and Trash
5. Script fails because .cache does not exist
6. Trash remains uncleaned

## Expected behavior
Script still runs Trash cleaning regardless of the failed cache-cleanup.

## Screenshots

screenshot-2024-10-20-12-28-25

screenshot-2024-10-20-12-28-47

## Additional context
Distro: Fedora 40. 
Happens with regular linutil and the dev branch too (linux and linuxdev)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by adamperkowski**
## Type of Change
- [x] Bug fix
- [x] Refactoring
- [x] UI/UX improvement

## Testing

Works :)

## Issues / other PRs related

- Resolves #855

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: core/tabs/system-setup/system-cleanup.sh [hunk 1]
```diff
@@ -26,16 +26,21 @@ cleanup_system() {
...
-    "$ESCALATION_TOOL" find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
+    if [ -d /var/tmp ]; then
+        "$ESCALATION_TOOL" find /var/tmp -type f -atime +5 -delete
+    fi
+    if [ -d /tmp ]; then
+        "$ESCALATION_TOOL" find /tmp -type f -atime +5 -delete
+    fi
+    if [ -d /var/log ]; then
+        "$ESCALATION_TOOL" find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
+    fi
```
Comment (jeevithakannan2) [inline core/tabs/system-setup/system-cleanup.sh:43]: Can we do something like this ?

```suggestion
    "$ESCALATION_TOOL" find /var/tmp -type f -atime +5 -delete &> /dev/null || true
    "$ESCALATION_TOOL" find /tmp -type f -atime +5 -delete &> || true
    "$ESCALATION_TOOL" find /var/log -type f -name "*.log" -exec truncate -s 0 {} \; &> || true
```

Comment (adamperkowski) [reply core/tabs/system-setup/system-cleanup.sh:43]: We could but if user doesnt have perms for a file (could happen and will happen with /tmp) it'll fail too

Comment (jeevithakannan2) [reply core/tabs/system-setup/system-cleanup.sh:43]: The cmd is escalated so there will no perm err

**Review by ChrisTitusTech — APPROVED** [review]
