### PR TITLE
📃 fix(system-cleanup): pacman orphan package removal

### LINKED ISSUE #741: system cleanup wont work
Screenshot_20241003_021555

i have no idea how to fix this or there is any problem on myside

### PR DESCRIPTION
**Pull request by adamperkowski**
## Type of Change]
- [x] Bug fix
- [x] Hotfix

## Description
As you can see below, the script fails because:
1. Command structure for package removal is wrong
2. `-R` returns `1` when there are no packages provided

All fixed here
Redirecting the output to `/dev/null` so the script's output doesn't get flooded. 

## Testing
Works :)

## Issues / other PRs related

- Resolves #741

## Additional Information
image

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

(📃 is a shell script btw)

### CODE REVIEW

File: core/tabs/system-setup/system-cleanup.sh [hunk 1]
```diff
@@ -23,7 +23,8 @@ cleanup_system() {
             ;;
         pacman)
             "$ESCALATION_TOOL" "$PACKAGER" -Sc --noconfirm
-            "$ESCALATION_TOOL" "$PACKAGER" -Rns "$(pacman -Qtdq)" --noconfirm
+            # -Rns will return 1 if there are no packages provided
```
Comment (nnyyxxxx) [inline core/tabs/system-setup/system-cleanup.sh:26]: remove note

Comment (nnyyxxxx) [inline core/tabs/system-setup/system-cleanup.sh:26]:
```suggestion
```

**Comment by nnyyxxxx** [comment]
i swear this used to work must have been that new pacman update

**Comment by nnyyxxxx** [comment]
ah i see the issue
image
the issue is with the quoting, what you're doing here is completely unnecessary, just remove the quotes and then send the output to null

File: core/tabs/system-setup/system-cleanup.sh [hunk 2]
```diff
@@ -23,7 +23,8 @@ cleanup_system() {
...
+            "$PACKAGER" -Qtdq | "$ESCALATION_TOOL" "$PACKAGER" -Rns --noconfirm - > /dev/null 2>&1 || true
```
Comment (nnyyxxxx) [inline core/tabs/system-setup/system-cleanup.sh:27]:
```suggestion
            "$ESCALATION_TOOL" "$PACKAGER" -Rns $(pacman -Qtdq) --noconfirm > dev/null 2>&1
```

Comment (nnyyxxxx) [reply core/tabs/system-setup/system-cleanup.sh:27]: image

Comment (nnyyxxxx) [reply core/tabs/system-setup/system-cleanup.sh:27]: your way of doing will just slow the script down

**Review by nnyyxxxx — APPROVED** [review]
awesome

**Review by ChrisTitusTech — APPROVED** [review]
