### PR TITLE
📃 fix(zsh-setup): check if `/etc/zsh/zshenv` exists

### LINKED ISSUE #770: Running zsh setup resulted in error below in screenshot
## Describe the bug
Self explanatory

## Screenshots
swappy-20241005-201858

### PR DESCRIPTION
**Pull request by adamperkowski**
## Type of Change
- [x] Bug fix

## Description
`tee` fails if the file doesn't exist.

## Issues / other PRs related

- Resolves #770

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: core/tabs/applications-setup/zsh-setup.sh [hunk 1]
```diff
@@ -44,6 +44,7 @@ RPROMPT='%F{15}(%F{166}%D{%H:%M}%F{15})%f'
 EOL
 
   # Ensure /etc/zsh/zshenv sets ZDOTDIR to the user's config directory
+  [ ! -f /etc/zsh/zshenv ] && "$ESCALATION_TOOL" touch /etc/zsh/zshenv
```
Comment (nnyyxxxx) [inline core/tabs/applications-setup/zsh-setup.sh:47]:
```suggestion
  [ ! -f /etc/zsh/zshenv ] && "$ESCALATION_TOOL" mkdir -p /etc/zsh && touch /etc/zsh/zshenv
```

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]

File: core/tabs/applications-setup/zsh-setup.sh (hunk 1 above)
Comment (nnyyxxxx) [reply core/tabs/applications-setup/zsh-setup.sh:47]: -p flag only creates the dir if it doesn't already exist

**Review by ChrisTitusTech — APPROVED** [review]
