### PR TITLE
fix: Correctly Detect Pictures Directory and Clone Path for Background

### LINKED ISSUE #303: DWM-Titus Background Installation Bug Fedora 40
## Describe the bug
When the [dwmtitus-setup.sh](https://github.com/ChrisTitusTech/linutil/blob/main/src/commands/applications-setup/dwmtitus-setup.sh) script is called when trying to run the DWM-Titus Application Setup on Fedora Server 40 the `configure_backgrounds` function can not detect whether or not the `~/Pictures` directory already exists. Also the clone is too shallow causing the `mv` command to fail.

## To Reproduce
1. Create an empty `Pictures` directory in your home dir
2. Go to Applications Setup and select  DWM-Titus
3. Fill in your elevation passwords in order to continue down to where dwm is compiled
4. You will see in the logs *Pictures directory does not exist* and then it will try to make the directory and fail because it already exists.
5. Then the clone of the images will happen anyways but there will be no `nord-background` folder, the images will just be at the top level `Pictures` directory

## Expected behavior
The script detects whether or not there's a Pictures directory. Creates it if so, otherwise clones the [nord-background](https://github.com/ChrisTitusTech/nord-background) repo into `~/Pictures/nord-background`

## Screenshots

Here is the image of having an empty Pictures directory

image

Running the `DWM-Titus` task

image

Here is what you wind up with in `Pictures`

image

### PR DESCRIPTION
**Pull request by rdunne2020**
# Pull Request

## Title
Correctly Detect Pictures Directory and Clone Path for Background

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation Update
- [x] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

The `configure_background` function couldn't correctly detect existing `Pictures` directory and installed the `nord-background` repo to the top level of the `Pictures` directory

https://github.com/ChrisTitusTech/linutil/issues/303

## Testing
Tested both having no `Pictures` directory and an existing `Pictures` directory, then ran the `DWM-Titus` script from the TUI. Both times the images from the `nord-background` repository wound up in `~/Pictures/background`

## Impact
N/A

## Issue related to PR

- Resolves #303 

## Additional Information

This will still fail if you already have a `~/Pictures/nord-background` folder that's not empty but that seemed a bit extra to go clobbering that if it existed.

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: src/commands/applications-setup/dwmtitus-setup.sh [hunk 1]
```diff
@@ -290,9 +293,9 @@ setupDisplayManager() {
             echo "Auto-login configuration skipped"
         fi
     fi
-    
 
-    
+
+
```
Comment (nnyyxxxx) [inline src/commands/applications-setup/dwmtitus-setup.sh:298]: Remove these 3 extra lines.

Comment (rdunne2020) [reply src/commands/applications-setup/dwmtitus-setup.sh]: I believe I got it

Comment (nnyyxxxx) [reply src/commands/applications-setup/dwmtitus-setup.sh]: Thanks.

**Review by nnyyxxxx — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Sorry for the inconvenience. We had a massive restructure of the codebase to improve future development. Because of this can you update your PR to the new structure. Thank you for your assistance and contribution.

**Comment by rdunne2020** [comment]
Rebased on top of the new change

**Review by ChrisTitusTech — APPROVED** [review]
