### PR TITLE
fix: Debian && popos gaming deps

### LINKED ISSUE #851: Not installing game dependencies; cannot handle repository shortcut
## Describe the bug
Attempt to install Gaming Dependencies under System Setup

## To Reproduce
1. Go to System Setup > Gaming dependencies
2. Click on Gaming dependencies
3. Enter password and attempt to install dependencies
4. See error "Unable to handle repository shortcut 'contrib'"

## Expected behavior
I expect dependencies to be sorted and installed

## Checklist
- [ X] I checked for duplicate issues.
- [ X] I checked already existing discussions.
- [ X] This issue is not included in the roadmap.

## Additional information
Screenshot from 2024-10-20 00-17-03

Computer is running PopOS 22.04 LTS

### LINKED ISSUE #852: Debian gaming dependencies libsdl2 not found
## Describe the bug
Debian gaming dependencies installation failure 

## Expected behavior
Install gaming dependencies

## Screenshots
image

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
- Add `git` as a dependency because getting version info for lutris requires `git`
- Correct package name for `libsdl2` => `libsdl2-2.0-0`
- Removed redundant update command
- No confirm installation for lutris
- Replace unnecessary package install code with unsupported package manager message
- Remove some comments

## Testing
- Tested on fresh install of debian12 and pop-os 22

## Issues / other PRs related
- Resolves #851 
- Resolves #852 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: core/tabs/system-setup/gaming-setup.sh [hunk 1]
```diff
@@ -26,12 +25,12 @@ installDepend() {
...
-            DISTRO_DEPS="libasound2 libsdl2 wine64 wine32"
+            DISTRO_DEPS="software-properties-common libasound2 libsdl2-2.0-0 wine64 wine32"
 
-            "$ESCALATION_TOOL" "$PACKAGER" update
             "$ESCALATION_TOOL" dpkg --add-architecture i386
-            "$ESCALATION_TOOL" "$PACKAGER" install -y software-properties-common
-            "$ESCALATION_TOOL" apt-add-repository contrib -y
+            if [ "$DTYPE" != "pop" ]; then
+                "$ESCALATION_TOOL" apt-add-repository contrib -y
+            fi
```
Comment (lj3954) [inline core/tabs/system-setup/gaming-setup.sh:33]: What's the benefit of skipping this command? Will it fail on Pop!_OS systems, or is it just unnecessary? I think it's rather unnecessary to check for the case of one distro if it's the latter.

The `software-properties-common` package also includes add-apt-repository (and this symlink, apt-add-repository); we cannot move its installation to after running this command.

**Review by lj3954 — CHANGES_REQUESTED** [review]

File: core/tabs/system-setup/gaming-setup.sh (hunk 1 above)
Comment (jeevithakannan2) [reply core/tabs/system-setup/gaming-setup.sh:33]: Pop os doesn't require contrib

Comment (lj3954) [reply core/tabs/system-setup/gaming-setup.sh:33]: Okay. Please move the software-properties-common installation into the body of the if statement.

**Review by lj3954 — APPROVED** [review]

**Review by adamperkowski — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]
