### PR TITLE
fix problems with debian 12

### LINKED ISSUE #570: Fastfetch fails to install
## Describe the bug
Fastfetch fails to install linutil says success but doesn't install (this is in Debian 12)
fastfetchfail

## Checklist
- [ ] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by nnyyxxxx**
image

## Type of Change
- [x] Bug fix

## Description
fix problems with fastfetch not being a package on debian 12 and only being a package on debian 13

## Issues / other PRs related

- Resolves #570 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: core/tabs/applications-setup/fastfetch-setup.sh [hunk 1]
```diff
@@ -9,6 +9,11 @@ installFastfetch() {
             pacman)
                 "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm fastfetch
                 ;;
+            apt-get|nala)
+                curl -sSLo /tmp/fastfetch.deb https://github.com/fastfetch-cli/fastfetch/releases/download/2.25.0/fastfetch-linux-amd64.deb
```
Comment (adamperkowski) [inline core/tabs/applications-setup/fastfetch-setup.sh:13]: What about future releases?

Comment (nnyyxxxx) [reply core/tabs/applications-setup/fastfetch-setup.sh]: resolved

**Review by adamperkowski — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]
