### PR TITLE
fix(dwm-titus): Multiple fixes

### LINKED ISSUE #1005: Failed to Install DWM on Fedora Linux
## Describe the bug
I am using Fedora 41 Workstation, and I encountered an error while running the DWM Titus script:

```sh
Unknown argument "groupinstall" for command "dnf5". Add "--help" for more information about the arguments.
It could be a command provided by a plugin, try: dnf5 install 'dnf5-command(groupinstall)'
```

## To Reproduce
- Use the latest version of LinUtil.
- Navigate to the DWM Titus script in the TUI.
- Run the script to install DWM and observe the error.

## Expected behavior
The script should install DWM Titus, as it works for me on Arch Linux.

## Screenshots

Image

## Additional context
I believe the issue is related to the dwm-titus.sh script.

Image

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by Jaredy899**
## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Added picom depends for apt, dnf, and zypper. Added Zypper, and Alpine for install. Slight change in dm check. 

## Testing
Tested in Arch, Fedora 41, Debian, Opensuse Tumbleweed, Alpine

## Issues / other PRs related

- Resolves #1005 

## Additional Information
I know Chris may be picky about touching dwmtitus... 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: core/tabs/applications-setup/dwmtitus-setup.sh [hunk 1]
```diff
@@ -35,8 +63,8 @@ install_nerd_font() {
     FONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip"
     FONT_INSTALLED=$(fc-list | grep -i "Meslo")
 
-    # Replace -n test with standard test
-    if [ ! -z "$FONT_INSTALLED" ]; then
+    # Check if Meslo Nerd-font is already installed
```
Comment (adamperkowski) [inline core/tabs/applications-setup/dwmtitus-setup.sh:66]:
```suggestion
```

**Review by adamperkowski — APPROVED** [review]
LGTM! cc @ChrisTitusTech good to merge

**Comment by Jaredy899** [comment]
Made some adjustments to take advantage of the common-service-script for consistency. (I'm testing this script with void whenever that gets added)

**Comment by Jaredy899** [comment]
@adamperkowski Can you check everything again? I changed a few things and added alpine.

**Review by adamperkowski — CHANGES_REQUESTED** [review]
there are some errors here. take a look at the CI

**Comment by Jaredy899** [comment]
@adamperkowski I corrected my error and addressed the other problems that shellcheck was catching. Did a quick test on all the distros and it works

**Review by adamperkowski — APPROVED** [review]
thanks for the quick fix. lgtm

**Review by ChrisTitusTech — APPROVED** [review]
