### PR TITLE
fix: Autocpu-freq script not detecting battery on laptops

### LINKED ISSUE #871: Auto cpu-freq fails to detect laptop
## Describe the bug
Auto cpu-freq fails to detect laptop. And fails to apply tweaks after installation.

## To Reproduce
1. Go to 'utilites'
2. Click on 'Auto Power Profiling'
3. Install 'auto cpu-freq'
4. Apply tweaks
5. See error

## Expected behavior
Able to detect laptop.

## Screenshots
image

## Additional context
Some laptops does not have battery in BAT0 instead they have in BAT1 or BAT2.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by infstate**
## Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description

* Added better checking when searching /sys/class/power_supply/ directory
* Uses ls with * wildcard to find all battery entries not limited to BAT0. (e.g. BAT1, BAT2)

## Testing
I have tested this on my Arch Linux install on DESKTOP. (no battery) 
However it should work.

## Impact
All this does is if there is any battery it will run the function for laptops and not desktops. 
It fixes the issue of not detecting a laptop and instead runs the power profile meant for desktops.

## Issues / other PRs related

- Resolves #871

## Checklist
- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: core/tabs/utils/power-profile.sh [hunk 1]
```diff
@@ -45,7 +45,7 @@ configureAutoCpufreq() {
 
     if command_exists auto-cpufreq; then
         # Check if the system has a battery to determine if it's a laptop
-        if [ -d /sys/class/power_supply/BAT0 ]; then
+        if ls /sys/class/power_supply/BAT* >/dev/null 2>&1; then     # Check if the system has a battery (laptop) by looking for any battery directory
```
Comment (nnyyxxxx) [inline core/tabs/utils/power-profile.sh:48]:
```suggestion
        if ls /sys/class/power_supply/BAT* >/dev/null 2>&1; then
 ```
this is self explanatory, no need for the comment

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]

**Review by adamperkowski — APPROVED** [review]
Thanks

**Comment by infstate** [comment]
Alright, thanks for the suggestions, I have removed the comment.

**Review by jeevithakannan2 — APPROVED** [review]

**Comment by jeevithakannan2** [comment]
This doesn't solve the error that occurs after installation.

Add these lines after installation steps

`sudo auto-cpufreq --install`

**Review by jeevithakannan2 — CHANGES_REQUESTED** [review]
While this solves the laptop issue. This doesn't solve the error that occurs after installation.

Add these lines after installation steps

`sudo auto-cpufreq --install`

**Comment by nnyyxxxx** [comment]
> While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> 
> Add these lines after installation steps
> 
> `sudo auto-cpufreq --install`

that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo

**Comment by jeevithakannan2** [comment]
> > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > Add these lines after installation steps
> > `sudo auto-cpufreq --install`
> 
> that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo

The issue mentions two issues and this PR only resolves only one issue.

And I just copy pasted the sudo auto-cpufreq --install from the err log

**Comment by nnyyxxxx** [comment]
> > > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > > Add these lines after installation steps
> > > `sudo auto-cpufreq --install`
> > 
> > 
> > that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo
> 
> The issue mentions two issues and this PR only resolves only one issue.
> 
> And I just copy pasted the sudo auto-cpufreq --install from the err log

again, ``sudo auto-cpufreq --install`` is not related to this pull request, please re read the PR title and description

**Comment by jeevithakannan2** [comment]
> > > > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > > > Add these lines after installation steps
> > > > `sudo auto-cpufreq --install`
> > > 
> > > 
> > > that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo
> > 
> > 
> > The issue mentions two issues and this PR only resolves only one issue.
> > And I just copy pasted the sudo auto-cpufreq --install from the err log
> 
> again, `sudo auto-cpufreq --install` is not related to this pull request, please re read the PR title and description

Then it does not resolve that issue completely. Please re-read the issue !!

**Comment by nnyyxxxx** [comment]
> > > > > While this solves the laptop issue. This doesn't solve the error that occurs after installation.
> > > > > Add these lines after installation steps
> > > > > `sudo auto-cpufreq --install`
> > > > 
> > > > 
> > > > that is not related to this pull request, and it should be used with $ESCALATION_TOOL not sudo
> > > 
> > > 
> > > The issue mentions two issues and this PR only resolves only one issue.
> > > And I just copy pasted the sudo auto-cpufreq --install from the err log
> > 
> > 
> > again, `sudo auto-cpufreq --install` is not related to this pull request, please re read the PR title and description
> 
> Then it does not resolve that issue completely. Please re-read the issue !!

ok? and is that my problem? why should i read the issue, once again ``sudo auto-cpufreq --install`` is not related to this pull request, please re read the pr title and description one more time !!

**Comment by nnyyxxxx** [comment]
issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or implementations, if you want you can split your issue into 2 since that would be better

**Comment by jeevithakannan2** [comment]
> issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better

I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.

**Comment by nnyyxxxx** [comment]
> > issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better
> 
> I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.

please re read the message you're responding to !!, that second issue is not related to this PR at all and should not be included

**Comment by jeevithakannan2** [comment]
> > > issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better
> > 
> > 
> > I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.
> 
> please re read the message you're responding to !!, that second issue is not related to this PR at all and should not be included

Waste of time and resources for a simple fix.

**Comment by nnyyxxxx** [comment]
> > > > issues and pull requests should be focused on 1 bug, or 1 implementation, they should not include multiple bugs or multiple implementations, if you want you can split your issue into 2 since that would be better
> > > 
> > > 
> > > I am getting what you're trying to say but this is not a big change. Not going to waste time on two separate PRs and issues while it can be easily fixed by adding a line in single PR.
> > 
> > 
> > please re read the message you're responding to !!, that second issue is not related to this PR at all and should not be included
> 
> Waste of time and resources for a simple fix.

re read the reply chain one more time !! maybe you'll understand the issue we're arguing about

**Review by nnyyxxxx — APPROVED** [review]
awesome

**Comment by infstate** [comment]
What in tarnation is going on here, doesn't it run the autocpu-freq --install on line 37 of the install function?

**Comment by jeevithakannan2** [comment]
> What in tarnation is going on here, doesn't it run the autocpu-freq --install on line 37 of the install function?

Looks like I was hallucinating. When I took the SS that line was not called. See the SS in the issue.

**Comment by nnyyxxxx** [comment]
looks like theres an extra space separating escalation tool on that line

**Comment by jeevithakannan2** [comment]
> looks like theres an extra space separating escalation tool on that line

Yeah but that shouldn't cause issues. I cannot reproduce the issue again.

**Comment by infstate** [comment]
If you want I can remove the extra space...

**Review by jeevithakannan2 — APPROVED** [review]

**Comment by adamperkowski** [comment]
damn what happened here
thats a lot of words

**Review by ChrisTitusTech — APPROVED** [review]
