### PR TITLE
refact(installer, updater): formatting & small fixes

### LINKED ISSUE #955: Installing linutil on Fedora 41
Good morning,

when I try to install Linutil on Fedora 41, I do get this error message.

Screenshot From 2024-11-18 08-16-26

Thank you.

### PR DESCRIPTION
**Pull request by jeevithakannan2**
## Type of Change
- [x] Bug fix
- [x] Refactoring

## Description
Installer -> Remove unreachable pacman case. dnf requires rustup-init before using rustup-init. Source .cargo/env after the installation of rustup.

Updater -> Formatting, Install rustup from dnf, change the wild case to use rustup.rs general installer from rust. Source the .cargo/env after the installation of rustup.

## Testing
- Tested on fedora 41 without issues.

## Issues / other PRs related
- Resolves #955 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

File: core/tabs/applications-setup/linutil-installer.sh [hunk 1]
```diff
@@ -34,36 +34,33 @@ installLinutil() {
...
+                                rustup-init -y
                                 ;;
                             apk)
-                                "$ESCALATION_TOOL" "$PACKAGER" add build-base
-                                "$ESCALATION_TOOL" "$PACKAGER" add rustup
-                                rustup-init
-                                # shellcheck disable=SC1091
-                                . "$HOME/.cargo/env"
+                                "$ESCALATION_TOOL" "$PACKAGER" add build-base rustup
+                                rustup-init -y
```
Comment (adamperkowski) [inline core/tabs/applications-setup/linutil-installer.sh:47]:
```suggestion
```

File: core/tabs/applications-setup/linutil-updater.sh [hunk 2]
```diff
@@ -10,28 +10,31 @@ updateLinutil() {
...
-                    "$ESCALATION_TOOL" "$PACKAGER" install -y rustup
-                    ;;
-            esac
+        case "$PACKAGER" in
+            pacman)
+                "$ESCALATION_TOOL" "$PACKAGER" -S --needed --noconfirm rustup
+                ;;
+            dnf)
+                "$ESCALATION_TOOL" "$PACKAGER" install -y curl rustup man-pages man-db man
+                rustup-init -y
```
Comment (adamperkowski) [inline core/tabs/applications-setup/linutil-updater.sh:19]:
```suggestion
```

File: core/tabs/applications-setup/linutil-updater.sh [hunk 3]
```diff
@@ -10,28 +10,31 @@ updateLinutil() {
...
+                ;;
+            zypper)
+                "$ESCALATION_TOOL" "$PACKAGER" install -n curl gcc make rustup
+                ;;
+            apk)
+                "$ESCALATION_TOOL" "$PACKAGER" add build-base rustup
+                rustup-init -y
```
Comment (adamperkowski) [inline core/tabs/applications-setup/linutil-updater.sh:26]:
```suggestion
```

**Review by adamperkowski — CHANGES_REQUESTED** [review]

**Comment by jeevithakannan2** [comment]
No until you do rustup-init rustup command will not be available in fedora and alpine

**Review by adamperkowski — APPROVED** [review]
Oh okay then. Couldn't find any official documentation on it, that's why I commented.

**Review by ChrisTitusTech — APPROVED** [review]
