### PR TITLE
fix(compile-setup): Zypper Build Prerequistes

### LINKED ISSUE #1000: Zypper build dependency failure
## Describe the bug
When installing the build dependencies for Tumbleweed or Leap, tldr and trash-cli are not in the repos, so the install fails. 

## To Reproduce
Install Build Dependencies for Tumbleweed or Leap

## Expected behavior
to install build depends without failure

## Screenshots

{2CC9D82A-63FD-4153-874D-A193A68BD9FF}

## Additional context
Could take out tldr and trash-cli. 

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

### PR DESCRIPTION
**Pull request by Jaredy899**
## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Removed tldr and trash-cli as they are not in the zypper repos. 

## Testing
Tested on Tumbleweed and Leap

## Impact
Fixes openSUSE build prerequistes. 

## Issues / other PRs related

- Resolves #1000 

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

### CODE REVIEW

**Review by adamperkowski — APPROVED** [review]

File: core/tabs/system-setup/compile-setup.sh [hunk 1]
```diff
@@ -34,8 +34,8 @@ installDepend() {
         zypper)
             COMPILEDEPS='patterns-devel-base-devel_basis'
             "$ESCALATION_TOOL" "$PACKAGER" refresh 
-            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install "$DEPENDENCIES" "$COMPILEDEPS"
-            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install libgcc_s1-gcc7-32bit glibc-devel-32bit
+            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install "$COMPILEDEPS"
+            "$ESCALATION_TOOL" "$PACKAGER" --non-interactive install "$DEPENDENCIES libgcc_s1-gcc7-32bit glibc-devel-32bit"
```
Comment (jeevithakannan2) [inline core/tabs/system-setup/compile-setup.sh:38]: Um what are we doing here ?? PR body mentioned trash_cli and tldr was removed but that's not the case here. Looks like the last commit nuked it

**Review by jeevithakannan2 — CHANGES_REQUESTED** [review]

**Review by jeevithakannan2 — APPROVED** [review]

**Review by ChrisTitusTech — APPROVED** [review]
